# Configuration file for ebiose-core-vincent
ecosystem:
  nb_selected_agents_for_new_forge_cycle: 1
  nb_new_agent_to_add_after_forge_cycle: 10

forge:
  architect_agent_budget_ratio: 1.0
  genetic_operator_agent_budget_ratio: 1.0

llm_compute:
  request_timeout_in_minutes: 2
  max_retries: 1

evolution:
  tournament_size_ratio: 0.1
  replacement_ratio: 0.5
  # crossover_rate: 1.0 
  # mutation_rate: 0.1 
  # elitism_ratio: 0.0