"""Integration tests for agent creation and factory."""

import pytest
from pydantic import BaseModel

from ebiose.core.agent import Agent


def test_agent_initialization():
    """Test basic agent creation and initialization."""
    agent = Agent(
        name="test_agent",
        description="A test agent",
        agent_type=None,
    )

    assert agent.name == "test_agent"
    assert agent.description == "A test agent"
    assert agent.id is not None
    assert agent.agent_type is None


def test_agent_parent_relationships():
    """Test agent parent tracking."""
    agent = Agent(
        name="offspring",
        description="An offspring agent",
        parent_ids=["parent1", "parent2"],
    )

    assert len(agent.parent_ids) == 2
    assert "parent1" in agent.parent_ids
    assert "parent2" in agent.parent_ids


def test_agent_architect_agent_tracking():
    """Test architect and genetic operator agent tracking."""
    agent = Agent(
        name="generated_agent",
        description="Generated by architect",
        architect_agent_id="architect-123",
        genetic_operator_agent_id="operator-456",
    )

    assert agent.architect_agent_id == "architect-123"
    assert agent.genetic_operator_agent_id == "operator-456"


def test_agent_serialization():
    """Test agent can be serialized to dict/JSON."""
    agent = Agent(
        name="serializable_agent",
        description="Test serialization",
        agent_type="architect",
    )

    # Should be able to dump to dict
    agent_dict = agent.model_dump(mode="json", exclude={"agent_engine"})

    assert agent_dict["name"] == "serializable_agent"
    assert agent_dict["description"] == "Test serialization"
    assert agent_dict["agent_type"] == "architect"
    assert agent_dict["id"] is not None


def test_multiple_agents_have_unique_ids():
    """Test that multiple agents get unique IDs."""
    agent1 = Agent(name="agent1", description="First")
    agent2 = Agent(name="agent2", description="Second")
    agent3 = Agent(name="agent3", description="Third")

    ids = [agent1.id, agent2.id, agent3.id]
    assert len(ids) == len(set(ids))  # All IDs are unique


def test_agent_with_no_type():
    """Test agent without explicit type."""
    agent = Agent(
        name="untyped",
        description="No agent type specified",
    )

    assert agent.agent_type is None


def test_agent_with_architect_type():
    """Test agent marked as architect."""
    agent = Agent(
        name="architect",
        description="Architect agent",
        agent_type="architect",
    )

    assert agent.agent_type == "architect"


def test_agent_with_genetic_operator_type():
    """Test agent marked as genetic operator."""
    agent = Agent(
        name="operator",
        description="Genetic operator agent",
        agent_type="genetic_operator",
    )

    assert agent.agent_type == "genetic_operator"

